%{
#include<stdio.h>
%}
%token KEYWORDS OB CB OC CC VARIABLE NUMBER SPACE OPERATOR SC KEY LO OP
%%
F : S {printf("Valid Syntax");}
;
S : KEY OB VARIABLE OPERATOR NUMBER SC VARIABLE OPERATOR NUMBER SC VARIABLE OP CB E
  | KEY OB VARIABLE OPERATOR NUMBER SC VARIABLE OPERATOR VARIABLE SC VARIABLE OP CB E
;
E : OC T CC
;
T : VARIABLE OPERATOR NUMBER SC
  | VARIABLE OPERATOR VARIABLE SC
  ;
%%
int main()
{
	yyparse();
	return 0;
}
